name: Build and Publish image to Github container repository

on:
  workflow_dispatch:
  push:
    branches: [main, develop]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: [main]

# Cancel previous PR/branch runs when a new commit is pushed
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      MAIN_PROJECT_DIR: "src/AgricultureManager.CoreApp/"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore ${{ env.MAIN_PROJECT_DIR }}

      - name: Build
        run: dotnet build ${{ env.MAIN_PROJECT_DIR }} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ env.MAIN_PROJECT_DIR }} --no-restore --verbosity normal

  semantic-version:
    name: Semantic Versioning
    needs: build
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.semantic-release.outputs.new_version }}

    permissions:
      actions: read
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm install -g semantic-release semantic-release-dotnet @semantic-release/git @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/github
      
      - name: Run Semantic Release
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release | tee release.log
          VERSION=$(cat release.log | grep -oP '(?<=next release version is )[\d\.]+(-beta\.\d+)?')
          echo "new_version=$VERSION" >> $GITHUB_OUTPUT
          echo "New version: $VERSION"

  deploy:
    name: Deploy to GitHub Container Registry
    needs: [build, semantic-version]
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Determine Docker Tags
        id: determine-tags
        run: |
          if [[ "${{ needs.semantic-version.outputs.new_version }}" == *"beta"* ]]; then
            echo "tags=type=raw,value=pre" >> $GITHUB_ENV
          else
            echo "tags=type=raw,value=latest" >> $GITHUB_ENV
          fi
          echo "Version: ${{ needs.semantic-version.outputs.new_version }}"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=${{ needs.semantic-version.outputs.new_version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ needs.semantic-version.outputs.new_version }}
            type=semver,pattern={{major}},value=${{ needs.semantic-version.outputs.new_version }}
            ${{ env.tags }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: "{{defaultContext}}:src"
          file: "./AgricultureManager.CoreApp/Dockerfile"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
